spring:
  application:
    name: akss-service
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      DeafualtZone : http://localhost:8761/eureka  
        
